---
title: "Quickstart Guide for MSCMGARCH"
author: "Your Name"
date: "`r Sys.Date()`"
output: html_document
---

## Introduction

The MSCMGARCH package provides a Markov-switching multivariate GARCH model with copula-distributed innovations. It allows for the dynamic assessment of financial market interdependencies, capturing potential regime shifts in asymmetric tail dependence structures among volatility innovations in speculative return series.

## Installation

To install the MSCMGARCH package, you can use the following commands in R:

```r
# Install the devtools package if you don't have it already
install.packages("devtools")

# Install the MSCMGARCH package from GitHub
devtools::install_github("nutle/MSCMGARCH")
```

## Examples of Main Functions

Here are some examples of the main functions in the MSCMGARCH package.

### Simulate Data

You can simulate data from the Markov-switching multivariate GARCH model using the `Sim_MSCMGARCH` function:

```r
# Simulate data
sim_data <- Sim_MSCMGARCH(type = "Normal Gumbel", n = 1000, amount = 10, true_par = c(0.9, 0.2, 12), lower_bound = c(0, 0, 1), upper_bound = c(1, 1, 17), nc = 1, seed = 123)
```

### Estimate Model Parameters

You can estimate the model parameters using the `MLE_MSCMGARCH` function:

```r
# Estimate model parameters
estimation <- MLE_MSCMGARCH(r = sim_data, type = "Normal Gumbel", nc = 1)
```

### Perform Rolling Window Analysis

You can perform rolling window analysis for forecasting using the `rolling_window` function:

```r
# Perform rolling window analysis
forecast <- rolling_window(series = sim_data, type = "MS_CMGARCH", copula_type = c(4, 4, 4), asymmetric = FALSE, window_length = 250, portfolio_weights = c(0.5, 0.5), signs = NULL, nc = 1)
```

## Interpreting the Results

### Simulated Data

The `Sim_MSCMGARCH` function generates simulated data based on the specified parameters. The output is a list of simulated data sets.

### Estimated Model Parameters

The `MLE_MSCMGARCH` function estimates the model parameters using maximum likelihood estimation. The output is a list containing the estimated parameters and other relevant information.

### Rolling Window Analysis

The `rolling_window` function performs rolling window analysis for forecasting. The output is a list of forecasted values based on the specified parameters and window length.

