# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

# Function to perform eigenvalue decomposition on a matrix
eigen_value_decomposition_1 <- function(A) {
    .Call(`_MSCMGARCH_eigen_value_decomposition_1`, A)
}

# Function to simulate BEKK model
simulate_bekk <- function(theta, r) {
    .Call(`_MSCMGARCH_simulate_bekk`, theta, r)
}

# Function to create elimination matrix
elimination_mat <- function(n) {
    .Call(`_MSCMGARCH_elimination_mat`, n)
}

# Function to create commutation matrix
commutation_mat <- function(n) {
    .Call(`_MSCMGARCH_commutation_mat`, n)
}

# Function to create duplication matrix
duplication_mat <- function(n) {
    .Call(`_MSCMGARCH_duplication_mat`, n)
}

# Function to compute inverse of a matrix
inv_gen <- function(m) {
    .Call(`_MSCMGARCH_inv_gen`, m)
}

# Function to compute expected indicator value
expected_indicator_value <- function(r, signs) {
    .Call(`_MSCMGARCH_expected_indicator_value`, r, signs)
}

# Function to compute log-likelihood of BEKK model
loglike_bekk <- function(theta, r) {
    .Call(`_MSCMGARCH_loglike_bekk`, theta, r)
}

# Function to compute log-likelihood of asymmetric BEKK model
loglike_asymm_bekk <- function(theta, r, signs) {
    .Call(`_MSCMGARCH_loglike_asymm_bekk`, theta, r, signs)
}

# Function to compute score of BEKK model
score_bekk <- function(theta, r) {
    .Call(`_MSCMGARCH_score_bekk`, theta, r)
}

# Function to compute score of asymmetric BEKK model
score_asymm_bekk <- function(theta, r, signs) {
    .Call(`_MSCMGARCH_score_asymm_bekk`, theta, r, signs)
}

# Function to perform BHH optimization for BEKK model
bhh_bekk <- function(r, theta, max_iter, crit) {
    .Call(`_MSCMGARCH_bhh_bekk`, r, theta, max_iter, crit)
}

# Function to perform BHH optimization for asymmetric BEKK model
bhh_asymm_bekk <- function(r, theta, max_iter, crit, signs) {
    .Call(`_MSCMGARCH_bhh_asymm_bekk`, r, theta, max_iter, crit, signs)
}

# Function to perform random grid search for BEKK model
random_grid_search_BEKK <- function(r) {
    .Call(`_MSCMGARCH_random_grid_search_BEKK`, r)
}

# Function to perform random grid search for asymmetric BEKK model
random_grid_search_asymmetric_BEKK <- function(r, signs) {
    .Call(`_MSCMGARCH_random_grid_search_asymmetric_BEKK`, r, signs)
}

# Function to compute sigma for BEKK model
sigma_bekk <- function(r, C, A, G) {
    .Call(`_MSCMGARCH_sigma_bekk`, r, C, A, G)
}

# Function to compute sigma for asymmetric BEKK model
sigma_bekk_asymm <- function(r, C, A, B, G, signs) {
    .Call(`_MSCMGARCH_sigma_bekk_asymm`, r, C, A, B, G, signs)
}

# Function to compute Hessian for BEKK model
hesse_bekk <- function(theta, r) {
    .Call(`_MSCMGARCH_hesse_bekk`, theta, r)
}

# Function to compute Hessian for asymmetric BEKK model
hesse_asymm_bekk <- function(theta, r, signs) {
    .Call(`_MSCMGARCH_hesse_asymm_bekk`, theta, r, signs)
}

# Function to compute pnorm using C++
pnorm_cpp <- function(r) {
    .Call(`_MSCMGARCH_pnorm_cpp`, r)
}

# Function to compute dnorm using C++
dnorm_cpp <- function(r) {
    .Call(`_MSCMGARCH_dnorm_cpp`, r)
}

# Function to compute Gumbel CDF
gumbelCDF <- function(u1, u2, theta) {
    .Call(`_MSCMGARCH_gumbelCDF`, u1, u2, theta)
}

# Function to compute Gumbel PDF
gumbelPDF <- function(u1, u2, theta) {
    .Call(`_MSCMGARCH_gumbelPDF`, u1, u2, theta)
}

# Function to compute raw Gumbel PDF
gumbelPDF_raw <- function(u1, u2, theta) {
    .Call(`_MSCMGARCH_gumbelPDF_raw`, u1, u2, theta)
}

# Function to compute Gumbel H1
gumbelH1 <- function(u1, u2, theta) {
    .Call(`_MSCMGARCH_gumbelH1`, u1, u2, theta)
}

# Function to compute Gumbel H2
gumbelH2 <- function(u1, u2, theta) {
    .Call(`_MSCMGARCH_gumbelH2`, u1, u2, theta)
}

# Function to compute Clayton CDF
claytonCDF <- function(u1, u2, theta) {
    .Call(`_MSCMGARCH_claytonCDF`, u1, u2, theta)
}

# Function to compute Clayton PDF
claytonPDF <- function(u1, u2, theta) {
    .Call(`_MSCMGARCH_claytonPDF`, u1, u2, theta)
}

# Function to compute raw Clayton PDF
claytonPDF_raw <- function(u1, u2, theta) {
    .Call(`_MSCMGARCH_claytonPDF_raw`, u1, u2, theta)
}

# Function to compute Clayton H1
claytonH1 <- function(u1, u2, theta) {
    .Call(`_MSCMGARCH_claytonH1`, u1, u2, theta)
}

# Function to compute Clayton H2
claytonH2 <- function(u1, u2, theta) {
    .Call(`_MSCMGARCH_claytonH2`, u1, u2, theta)
}

# Function to compute copula PDF
copulaPDF <- function(u1, u2, theta, type) {
    .Call(`_MSCMGARCH_copulaPDF`, u1, u2, theta, type)
}

# Function to compute copula H1
copulaH1 <- function(u1, u2, theta, type) {
    .Call(`_MSCMGARCH_copulaH1`, u1, u2, theta, type)
}

# Function to compute copula H2
copulaH2 <- function(u1, u2, theta, type) {
    .Call(`_MSCMGARCH_copulaH2`, u1, u2, theta, type)
}

# Function to compute Vine H2
VineH2 <- function(u1, u2, u3, copula_par, type) {
    .Call(`_MSCMGARCH_VineH2`, u1, u2, u3, copula_par, type)
}

# Function to compute Vine Copula
VineCopula <- function(u, copula_par, type) {
    .Call(`_MSCMGARCH_VineCopula`, u, copula_par, type)
}

# Function to perform eigenvalue decomposition
eigen_value_decomposition <- function(A) {
    .Call(`_MSCMGARCH_eigen_value_decomposition`, A)
}

# Function to compute log-likelihood for Normal Gumbel GumbelSurvival model
loglike_Normal_Gumbel_GumbelSurvival <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Normal_Gumbel_GumbelSurvival`, bekk, theta, r)
}

# Function to compute log-likelihood for Normal Gumbel Clayton model
loglike_Normal_Gumbel_Clayton <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Normal_Gumbel_Clayton`, bekk, theta, r)
}

# Function to compute log-likelihood for Normal GumbelS ClaytonS model
loglike_Normal_GumbelS_ClaytonS <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Normal_GumbelS_ClaytonS`, bekk, theta, r)
}

# Function to compute log-likelihood for Normal Clayton ClaytonSurvival model
loglike_Normal_Clayton_ClaytonSurvival <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Normal_Clayton_ClaytonSurvival`, bekk, theta, r)
}

# Function to compute log-likelihood for Clayton Gumbel model
loglike_Clayton_Gumbel <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Clayton_Gumbel`, bekk, theta, r)
}

# Function to compute log-likelihood for Clayton Gumbel90 model
loglike_Clayton_Gumbel90 <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Clayton_Gumbel90`, bekk, theta, r)
}

# Function to compute log-likelihood for Normal Gumbel model
loglike_Normal_Gumbel <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Normal_Gumbel`, bekk, theta, r)
}

# Function to compute log-likelihood for Normal GumbelS model
loglike_Normal_GumbelS <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Normal_GumbelS`, bekk, theta, r)
}

# Function to compute log-likelihood for Normal Gumbel1 model
loglike_Normal_Gumbel1 <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Normal_Gumbel1`, bekk, theta, r)
}

# Function to compute log-likelihood for Normal GumbelS1 model
loglike_Normal_GumbelS1 <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Normal_GumbelS1`, bekk, theta, r)
}

# Function to compute log-likelihood for Normal Frank model
loglike_Normal_Frank <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Normal_Frank`, bekk, theta, r)
}

# Function to compute log-likelihood for Normal Clayton1 model
loglike_Normal_Clayton1 <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Normal_Clayton1`, bekk, theta, r)
}

# Function to compute log-likelihood for Normal ClaytonS model
loglike_Normal_ClaytonS <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Normal_ClaytonS`, bekk, theta, r)
}

# Function to compute log-likelihood for Normal Clayton model
loglike_Normal_Clayton <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Normal_Clayton`, bekk, theta, r)
}

# Function to compute log-likelihood for Normal ClaytonS1 model
loglike_Normal_ClaytonS1 <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_loglike_Normal_ClaytonS1`, bekk, theta, r)
}

# Function to perform random grid search for Clayton Gumbel model
random_grid_search_clayton_gumbel <- function(bekk, theta, r, nc) {
    .Call(`_MSCMGARCH_random_grid_search_clayton_gumbel`, bekk, theta, r, nc)
}

# Function to perform random grid search for Normal Gumbel model
random_grid_search_normal_gumbel <- function(bekk, theta, r, nc) {
    .Call(`_MSCMGARCH_random_grid_search_normal_gumbel`, bekk, theta, r, nc)
}

# Function to perform random grid search for Normal Gumbel1 model
random_grid_search_normal_gumbel1 <- function(bekk, theta, r, nc) {
    .Call(`_MSCMGARCH_random_grid_search_normal_gumbel1`, bekk, theta, r, nc)
}

# Function to perform random grid search for Normal GumbelS model
random_grid_search_normal_gumbelS <- function(bekk, theta, r, nc) {
    .Call(`_MSCMGARCH_random_grid_search_normal_gumbelS`, bekk, theta, r, nc)
}

# Function to perform random grid search for Normal Clayton model
random_grid_search_normal_clayton <- function(bekk, theta, r, nc) {
    .Call(`_MSCMGARCH_random_grid_search_normal_clayton`, bekk, theta, r, nc)
}

# Function to perform random grid search for Normal ClaytonS model
random_grid_search_normal_claytonS <- function(bekk, theta, r, nc) {
    .Call(`_MSCMGARCH_random_grid_search_normal_claytonS`, bekk, theta, r, nc)
}

# Function to perform random grid search for Normal Frank model
random_grid_search_normal_frank <- function(bekk, theta, r, nc) {
    .Call(`_MSCMGARCH_random_grid_search_normal_frank`, bekk, theta, r, nc)
}

# Function to perform random grid search for Clayton Gumbel90 model
random_grid_search_clayton_gumbel90 <- function(bekk, theta, r, nc) {
    .Call(`_MSCMGARCH_random_grid_search_clayton_gumbel90`, bekk, theta, r, nc)
}

# Function to perform random grid search for Normal Gumbel GumbelSurvival model
random_grid_search_normal_gumbel_gumbelsurvival <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_random_grid_search_normal_gumbel_gumbelsurvival`, bekk, theta, r)
}

# Function to perform random grid search for Normal GumbelS ClaytonS model
random_grid_search_normal_gumbelS_claytonS <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_random_grid_search_normal_gumbelS_claytonS`, bekk, theta, r)
}

# Function to perform random grid search for Normal Gumbel Clayton model
random_grid_search_normal_gumbel_clayton <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_random_grid_search_normal_gumbel_clayton`, bekk, theta, r)
}

# Function to perform random grid search for Normal Clayton ClaytonSurvival model
random_grid_search_normal_clayton_claytonsurvival <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_random_grid_search_normal_clayton_claytonsurvival`, bekk, theta, r)
}

# Function to compute filter probabilities for Normal Clayton ClaytonS model
FilterProbs_normal_clayton_claytonS <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_FilterProbs_normal_clayton_claytonS`, bekk, theta, r)
}

# Function to compute filter probabilities for Normal Gumbel Clayton model
FilterProbs_normal_gumbel_clayton <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_FilterProbs_normal_gumbel_clayton`, bekk, theta, r)
}

# Function to compute filter probabilities for Normal GumbelS ClaytonS model
FilterProbs_normal_gumbelS_claytonS <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_FilterProbs_normal_gumbelS_claytonS`, bekk, theta, r)
}

# Function to compute filter probabilities for Normal Gumbel GumbelS model
FilterProbs_normal_gumbel_gumbelS <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_FilterProbs_normal_gumbel_gumbelS`, bekk, theta, r)
}

# Function to compute filter probabilities for Clayton Gumbel90 model
FilterProbs_Clayton_Gumbel90 <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_FilterProbs_Clayton_Gumbel90`, bekk, theta, r)
}

# Function to compute filter probabilities for Normal Gumbel model
FilterProbs_Normal_Gumbel <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_FilterProbs_Normal_Gumbel`, bekk, theta, r)
}

# Function to compute filter probabilities for Normal Clayton model
FilterProbs_Normal_Clayton <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_FilterProbs_Normal_Clayton`, bekk, theta, r)
}

# Function to compute filter probabilities for Normal GumbelS model
FilterProbs_Normal_GumbelS <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_FilterProbs_Normal_GumbelS`, bekk, theta, r)
}

# Function to compute filter probabilities for Normal ClaytonS model
FilterProbs_Normal_ClaytonS <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_FilterProbs_Normal_ClaytonS`, bekk, theta, r)
}

# Function to compute filter probabilities for Normal Frank model
FilterProbs_Normal_Frank <- function(bekk, theta, r) {
    .Call(`_MSCMGARCH_FilterProbs_Normal_Frank`, bekk, theta, r)
}

# Function to compute log-likelihood for Gumbel model
loglike_LL_Gumbel <- function(theta, r) {
    .Call(`_MSCMGARCH_loglike_LL_Gumbel`, theta, r)
}

# Function to compute log-likelihood for GumbelS model
loglike_LL_GumbelS <- function(theta, r) {
    .Call(`_MSCMGARCH_loglike_LL_GumbelS`, theta, r)
}

# Function to compute log-likelihood for Clayton model
loglike_LL_Clayton <- function(theta, r) {
    .Call(`_MSCMGARCH_loglike_LL_Clayton`, theta, r)
}

# Function to compute log-likelihood for ClaytonS model
loglike_LL_ClaytonS <- function(theta, r) {
    .Call(`_MSCMGARCH_loglike_LL_ClaytonS`, theta, r)
}

# Function to compute log-likelihood for Frank model
loglike_LL_Frank <- function(theta, r) {
    .Call(`_MSCMGARCH_loglike_LL_Frank`, theta, r)
}

# Function to compute BEKK forecast
comp_bekk_forecast <- function(bekk, r) {
    .Call(`_MSCMGARCH_comp_bekk_forecast`, bekk, r)
}

# Function to compute asymmetric BEKK forecast
comp_asymm_bekk_forecast <- function(bekk, r, signs) {
    .Call(`_MSCMGARCH_comp_asymm_bekk_forecast`, bekk, r, signs)
}

# Function to compute copula correlation matrix
copula_cor <- function(theta, type) {
    .Call(`_MSCMGARCH_copula_cor`, theta, type)
}

# Function to compute correlation matrix
cor_mat <- function(theta, type) {
    .Call(`_MSCMGARCH_cor_mat`, theta, type)
}

# Function to compute log-likelihood for Normal Copula 3 model
loglike_Normal_Copula_3 <- function(bekk, theta, r, type) {
    .Call(`_MSCMGARCH_loglike_Normal_Copula_3`, bekk, theta, r, type)
}

# Function to compute log-likelihood for Normal Copula 3 asymmetric model
loglike_Normal_Copula_3_asymm <- function(bekk, signs, theta, r, type) {
    .Call(`_MSCMGARCH_loglike_Normal_Copula_3_asymm`, bekk, signs, theta, r, type)
}

# Function to compute log-likelihood for Normal Copula Copula 3 model
loglike_Normal_Copula_Copula_3 <- function(bekk, theta, r, type) {
    .Call(`_MSCMGARCH_loglike_Normal_Copula_Copula_3`, bekk, theta, r, type)
}

# Function to compute log-likelihood for Normal Copula Copula 3 asymmetric model
loglike_Normal_Copula_Copula_3_asymm <- function(bekk, signs, theta, r, type) {
    .Call(`_MSCMGARCH_loglike_Normal_Copula_Copula_3_asymm`, bekk, signs, theta, r, type)
}

# Function to compute log-likelihood for Copula 3 model
LL_loglike_Copula_3 <- function(theta, r, type) {
    .Call(`_MSCMGARCH_LL_loglike_Copula_3`, theta, r, type)
}

# Function to compute log-likelihood for Copula 3 asymmetric model
LL_loglike_Copula_3_asymm <- function(theta, signs, r, type) {
    .Call(`_MSCMGARCH_LL_loglike_Copula_3_asymm`, theta, signs, r, type)
}

# Function to perform random grid search for Normal Copula 3 model
random_grid_search_normal_copula_3 <- function(bekk, theta, type, r, nc) {
    .Call(`_MSCMGARCH_random_grid_search_normal_copula_3`, bekk, theta, type, r, nc)
}

# Function to perform random grid search for Normal Copula Copula 3 model
random_grid_search_normal_copula_copula_3 <- function(bekk, theta, type, r, nc) {
    .Call(`_MSCMGARCH_random_grid_search_normal_copula_copula_3`, bekk, theta, type, r, nc)
}

# Function to perform random grid search for Normal Copula 3 asymmetric model
random_grid_search_normal_copula_3_asymm <- function(bekk, signs, theta, type, r, nc) {
    .Call(`_MSCMGARCH_random_grid_search_normal_copula_3_asymm`, bekk, signs, theta, type, r, nc)
}

# Function to perform random grid search for Normal Copula Copula 3 asymmetric model
random_grid_search_normal_copula_copula_3_asymm <- function(bekk, signs, theta, type, r, nc) {
    .Call(`_MSCMGARCH_random_grid_search_normal_copula_copula_3_asymm`, bekk, signs, theta, type, r, nc)
}

# Function to compute filter probabilities for Normal Copula 3 model
FilterProbs_Normal_Copula_3 <- function(bekk, theta, r, type) {
    .Call(`_MSCMGARCH_FilterProbs_Normal_Copula_3`, bekk, theta, r, type)
}

# Function to compute filter probabilities for Normal Copula 3 asymmetric model
FilterProbs_Normal_Copula_3_asymm <- function(bekk, signs, theta, r, type) {
    .Call(`_MSCMGARCH_FilterProbs_Normal_Copula_3_asymm`, bekk, signs, theta, r, type)
}

# Function to compute filter probabilities for Normal Copula Copula 3 model
FilterProbs_Normal_Copula_Copula_3 <- function(bekk, theta, r, type) {
    .Call(`_MSCMGARCH_FilterProbs_Normal_Copula_Copula_3`, bekk, theta, r, type)
}

# Function to compute filter probabilities for Normal Copula Copula 3 asymmetric model
FilterProbs_Normal_Copula_Copula_3_asymm <- function(bekk, signs, theta, r, type) {
    .Call(`_MSCMGARCH_FilterProbs_Normal_Copula_Copula_3_asymm`, bekk, signs, theta, r, type)
}

# Function to perform random grid search for Copula 3 model
random_grid_search_LL_copula_3 <- function(theta, r, type, nc) {
    .Call(`_MSCMGARCH_random_grid_search_LL_copula_3`, theta, r, type, nc)
}

# Function to perform random grid search for Copula 3 asymmetric model
random_grid_search_LL_copula_3_asymm <- function(theta, signs, r, type, nc) {
    .Call(`_MSCMGARCH_random_grid_search_LL_copula_3_asymm`, theta, signs, r, type, nc)
}
